#!/usr/bin/env python3
"""Pull a big, diverse batch from Audius and seed a RADI0 station.

Audius is the web music library that already streams in the app: stable URLs
(no tokens/hotlink walls), full-length, legal (open catalog). This sweeps
trending + underground across several genres, dedups, and emits the same seed
SQL shape as Tools/seed-underground-open.sql.

Usage:
  python3 Tools/seed-audius.py [station_uuid] [limit] > Tools/seed-audius.sql
Defaults: station = THE UNDERGROUND, limit = 200.
"""
import json, sys, time, urllib.request, urllib.parse

APP = "RADI0"
HOST = "https://discoveryprovider.audius.co"
UNDERGROUND = "ba13d3b9-a9c7-807d-b73b-065938f474b5"
station = sys.argv[1] if len(sys.argv) > 1 else UNDERGROUND
limit_total = int(sys.argv[2]) if len(sys.argv) > 2 else 200

# Trending sweeps that fit RADI0's lean, plus underground for depth. Invalid
# genres just return fewer rows — harmless.
SWEEPS = [
    ("/v1/tracks/trending/underground", {}),
    ("/v1/tracks/trending", {"genre": "Hip-Hop/Rap", "time": "week"}),
    ("/v1/tracks/trending", {"genre": "Electronic", "time": "week"}),
    ("/v1/tracks/trending", {"genre": "Trap", "time": "week"}),
    ("/v1/tracks/trending", {"genre": "R&B/Soul", "time": "week"}),
    ("/v1/tracks/trending", {"genre": "Pop", "time": "week"}),
    ("/v1/tracks/trending", {"genre": "Dubstep", "time": "week"}),
    ("/v1/tracks/trending", {"genre": "House", "time": "week"}),
    ("/v1/tracks/trending", {"genre": "Hip-Hop/Rap", "time": "month"}),
    ("/v1/tracks/trending", {"genre": "Electronic", "time": "month"}),
]


def fetch(path, params):
    q = {"app_name": APP, **params}
    url = HOST + path + "?" + urllib.parse.urlencode(q)
    req = urllib.request.Request(url, headers={"User-Agent": "RADI0-seed/1.0"})
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            return json.load(r).get("data", []) or []
    except Exception as e:
        sys.stderr.write(f"[warn] {path} {params}: {e}\n")
        return []


def sql_str(s):
    return "'" + s.replace("'", "''") + "'"


def main():
    seen, rows = {}, []
    for path, params in SWEEPS:
        for t in fetch(path, params):
            tid = t.get("id")
            if not tid or tid in seen:
                continue
            if t.get("is_streamable") is False or t.get("is_delete"):
                continue
            dur = int(t.get("duration") or 0)
            if dur < 45 or dur > 720:
                continue
            user = t.get("user") or {}
            seen[tid] = True
            rows.append({
                "tid": tid,
                "title": (t.get("title") or "Untitled").strip(),
                "artist": (user.get("name") or user.get("handle") or "Unknown").strip(),
                "artist_id": user.get("id") or tid,
                "dur": dur,
            })
        time.sleep(0.2)   # be polite to the discovery node
        if len(rows) >= limit_total:
            break
    rows = rows[:limit_total]
    if not rows:
        raise SystemExit("No Audius tracks fetched — discovery node down?")

    out = ["-- Audius -> RADI0 station seed (full-length, legal, stable URLs).",
           f"-- {len(rows)} tracks. Additive: keeps whatever the station already airs.",
           f"-- Station: {station}",
           "-- Generated by Tools/seed-audius.py. Safe to re-run (refreshes audio_url).",
           "BEGIN;",
           "WITH new_tracks(track_id, title, artist, artist_id, duration_seconds, audio_url) AS (",
           "  VALUES"]
    vals = []
    for r in rows:
        url = f"{HOST}/v1/tracks/{r['tid']}/stream?app_name={APP}"
        vals.append(
            f"    (md5('audius:{r['tid']}')::uuid,{sql_str(r['title'])},{sql_str(r['artist'])},"
            f"md5('audius-artist:{r['artist_id']}')::uuid,{r['dur']},{sql_str(url)})"
        )
    out.append(",\n".join(vals))
    out += ["), ins AS (",
            "  INSERT INTO radio_tracks (track_id, title, artist, artist_id, duration_seconds, audio_url)",
            "  SELECT n.track_id, n.title, n.artist, n.artist_id, n.duration_seconds, n.audio_url",
            "  FROM new_tracks n",
            "  ON CONFLICT (track_id) DO UPDATE SET audio_url = EXCLUDED.audio_url",
            "  RETURNING track_id",
            ")",
            f"INSERT INTO radio_station_tracks (station_id, track_id)",
            f"SELECT '{station}'::uuid, track_id FROM ins",
            "ON CONFLICT DO NOTHING;",
            "COMMIT;"]
    sys.stdout.write("\n".join(out) + "\n")
    sys.stderr.write(f"[seed-audius] {len(rows)} tracks -> station {station}\n")


if __name__ == "__main__":
    main()
