#!/usr/bin/env python3
"""Seed a RADI0 station from Jamendo — full-length, CC-licensed, legal streams.

Mirrors Tools/seed-underground-open.sql (the Audius pattern): every track becomes
a radio_tracks row keyed md5('jamendo:<id>')::uuid, linked to a station via
radio_station_tracks. ADDITIVE by default (no DELETE) — it never rips out what a
station already plays; ON CONFLICT just refreshes the audio_url.

Durability: we store the *audiodownload* URL (stable, unsigned, full MP3) instead
of the `audio` streaming URL (which carries an expiring `from=` token) so seeded
rows don't rot. Only tracks with audiodownload_allowed=true are kept.

Licensing: Jamendo tracks are Creative Commons. The free API + these URLs are for
NON-COMMERCIAL use with artist attribution (RADI0 shows artist names). If RADI0
ever monetizes, the tracks that expose prolicensing=true need a Jamendo Licensing
(commercial) agreement — flagged, not solved, here.

Usage:
  JAMENDO_CLIENT_ID=xxxx python3 Tools/seed-jamendo.py [station_uuid] [limit] > Tools/seed-jamendo.sql
Defaults: station = THE UNDERGROUND, limit = 60.
"""
import json, os, sys, urllib.request, urllib.parse

# The Client ID is the PUBLIC per-request identifier (like Audius' app_name=RADI0).
# The Client SECRET is never used here and must never be committed or shipped.
CLIENT_ID = os.environ.get("JAMENDO_CLIENT_ID", "2e5b0a50")
API = "https://api.jamendo.com/v3.0/tracks/"

UNDERGROUND = "ba13d3b9-a9c7-807d-b73b-065938f474b5"
station = sys.argv[1] if len(sys.argv) > 1 else UNDERGROUND
limit_total = int(sys.argv[2]) if len(sys.argv) > 2 else 60

# Pull from several angles that fit RADI0's lean (hip-hop / rap / electronic),
# plus a general popularity sweep, then merge + dedup. Each query is capped so no
# single genre dominates the station.
QUERIES = [
    {"order": "popularity_month", "tags": "hiphop",     "limit": "40"},
    {"order": "popularity_month", "tags": "rap",        "limit": "40"},
    {"order": "popularity_month", "tags": "electronic", "limit": "30"},
    {"order": "popularity_month", "tags": "lofi",       "limit": "20"},
    {"order": "popularity_total", "limit": "40"},
]


def fetch(params):
    q = {
        "client_id": CLIENT_ID, "format": "json",
        "include": "licenses", "audioformat": "mp32",
        # Only vocal/instrumental music that can be downloaded (=> stable URL).
        "audiodlallowed": "true",
        **params,
    }
    url = API + "?" + urllib.parse.urlencode(q)
    req = urllib.request.Request(url, headers={"User-Agent": "RADI0-seed/1.0"})
    with urllib.request.urlopen(req, timeout=30) as r:
        data = json.load(r)
    if data.get("headers", {}).get("status") != "success":
        raise SystemExit(f"Jamendo error: {data.get('headers')}")
    return data.get("results", [])


def sql_str(s):
    return "'" + s.replace("'", "''") + "'"


def main():
    seen, rows = {}, []
    for params in QUERIES:
        for t in fetch(params):
            tid = t.get("id")
            dl = t.get("audiodownload")
            if not tid or tid in seen or not dl:
                continue
            if not t.get("audiodownload_allowed"):
                continue
            dur = int(t.get("duration") or 0)
            if dur < 45 or dur > 900:   # skip stubs and 15-min ambient epics
                continue
            seen[tid] = True
            rows.append({
                "tid": tid, "name": t.get("name") or "Untitled",
                "artist": t.get("artist_name") or "Unknown",
                "artist_id": t.get("artist_id") or tid,
                "dur": dur, "url": dl,
            })
            if len(rows) >= limit_total:
                break
        if len(rows) >= limit_total:
            break

    if not rows:
        raise SystemExit("No Jamendo tracks fetched — check CLIENT_ID / network.")

    out = []
    out.append("-- Jamendo → RADI0 station seed (full-length, CC-licensed, legal).")
    out.append(f"-- {len(rows)} tracks. Additive: keeps whatever the station already airs.")
    out.append(f"-- Station: {station}")
    out.append("-- Generated by Tools/seed-jamendo.py. Safe to re-run (refreshes audio_url).")
    out.append("BEGIN;")
    out.append("WITH new_tracks(track_id, title, artist, artist_id, duration_seconds, audio_url) AS (")
    out.append("  VALUES")
    vals = []
    for r in rows:
        vals.append(
            f"    (md5('jamendo:{r['tid']}')::uuid,{sql_str(r['name'])},{sql_str(r['artist'])},"
            f"md5('jamendo-artist:{r['artist_id']}')::uuid,{r['dur']},{sql_str(r['url'])})"
        )
    out.append(",\n".join(vals))
    out.append("), ins AS (")
    out.append("  INSERT INTO radio_tracks (track_id, title, artist, artist_id, duration_seconds, audio_url)")
    out.append("  SELECT n.track_id, n.title, n.artist, n.artist_id, n.duration_seconds, n.audio_url")
    out.append("  FROM new_tracks n")
    out.append("  ON CONFLICT (track_id) DO UPDATE SET audio_url = EXCLUDED.audio_url")
    out.append("  RETURNING track_id")
    out.append(")")
    out.append(f"INSERT INTO radio_station_tracks (station_id, track_id)")
    out.append(f"SELECT '{station}'::uuid, track_id FROM ins")
    out.append("ON CONFLICT DO NOTHING;")
    out.append("COMMIT;")
    sys.stdout.write("\n".join(out) + "\n")
    sys.stderr.write(f"[seed-jamendo] {len(rows)} tracks → station {station}\n")


if __name__ == "__main__":
    main()
